<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_box_length" value="0.1" />
    <xacro:property name="arm_box_width" value="0.1" />
    <xacro:property name="arm_box_height" value="0.02" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />
    <xacro:property name="mass_arm_base" value="0.5" />
    <xacro:property name="mass_links_arm" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_box_length} ${arm_box_width} ${arm_box_height}" />
            </geometry>
            <origin xyz="0.0 0.0 ${arm_box_height / 2.0}" rpy="0.0 0.0 0.0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_box_length} ${arm_box_width} ${arm_box_height}" />
            </geometry>
            <origin xyz="0.0 0.0 ${arm_box_height / 2.0}" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:box_inertia m="${mass_arm_base}" l="${2*arm_box_length}" w="${2*arm_box_width}"
            h="${2*arm_box_height}" xyz="0.0 0.0 ${arm_box_height / 2.0}" rpy="0.0 0.0 0.0" />
    </link>

    <link name="forearm_link">
        <visual name="">
            <origin xyz="0.0 0.0 ${arm_length/2.0}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <material name="yellow" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${arm_length/2.0}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="${mass_links_arm}" r="${2*arm_radius}"
            h="${2*arm_length}" xyz="0.0 0.0 ${arm_length/2.0}" rpy="0.0 0.0 0.0" />
    </link>

    <link name="hand_link">
        <visual name="">
            <origin xyz="0.0 0.0 ${arm_length/2.0}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${arm_length/2.0}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="${mass_links_arm}" r="${2*arm_radius}"
            h="${2*arm_length}"
            xyz="0.0 0.0  ${arm_length/2.0}" rpy="0.0 0.0 0.0" />
    </link>


    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" velocity="100.0" effort="100.0" />
        <origin xyz="0 0 ${arm_box_height}" rpy="0 0 0" />
        <dynamics damping="0.05" friction="0.1" />
    </joint>


    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" velocity="100.0" effort="100.0" />
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0" />
        <dynamics damping="0.05" friction="0.1" />
    </joint>

    <gazebo>
        <plugin name="joint_state_publisher_controller"
            filename="libgazebo_ros_joint_state_publisher.so">
            <!-- Update rate in Hertz -->
            <update_rate>10</update_rate>

            <!-- Name of joints in the model whose states will be published. -->
            <joint_name>arm_base_forearm_joint</joint_name>
            <joint_name>forearm_hand_joint</joint_name>
        </plugin>
        <plugin name="joint_pose_trajectory_controller"
            filename="libgazebo_ros_joint_pose_trajectory.so">
            <update_rate>2</update_rate>
        </plugin>
    </gazebo>

    <gazebo reference="arm_base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="forearm_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="hand_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
</robot>